version: "3"

services:
  webserve:
    image: nginx:latest
    restart: always
    ports: 
      - "8080:80"
    volumes:
      - ./websites:/usr/share/nginx/html
    
    links:
      - db    


  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=felta1971
    restart: always
    volumes:
      - db_vol:/var/lib/mysql

volumes:
  db_vol:

 
